jwt:
  access:
    #JWT签发者
    iss: flcxi
    #JWT所面向的用户
    sub:
    #接收JWT的一方
    aud:
    #JWT的过期时间，这个过期时间必须要大于签发时间（ 签发时间+exp(ms)）
    exp: 30*60*1000
    #定义在什么时间之前，该JWT都是不可用的（ 签发时间+nbf(ms)）
    #nbf:
    #JWT的签发时间(默认当前时间)
    #iat:
    #JWT的唯一身份标识(主要用来作为一次性token,从而回避重放攻击)
    #id:
  refresh:
    #JWT签发者
    iss: flcxi
    #JWT所面向的用户
    sub:
    #接收JWT的一方
    aud:
    #JWT的过期时间，这个过期时间必须要大于签发时间（ 签发时间+exp(ms)）
    exp: 30*24*60*60*1000
    #定义在什么时间之前，该JWT都是不可用的（ 签发时间+nbf(ms)）
    #nbf:
    #JWT的签发时间(默认当前时间)
    #iat:
    #JWT的唯一身份标识(主要用来作为一次性token,从而回避重放攻击)
    #id:

